version: "3.8"
services:
  registry:
   image:registry:2
  ports:
   -"5000:5000"
  restart: unless-stopped

  jenkins:
    image: jenkins/jenkins:lts
     user:root
    ports:
     -"8080:8080"
     -"50000:50000"
    volumes:
     -jenkins_data:/var/jenkins_home
     -/var/run/docker.sock:var/run/docker.sock
    restart: unless-stopped

volumes:
 jenkins_data:



